package toks;

public enum TokType {
    UNKNOWN, VAR_DECL, CONST_DECL, FUN_DECL,
    ID, INT_LITERAL, FLOAT_LITERAL, BOOL_LITERAL,
    ADD, SUB, MUL, DIV, MOD, SHL, ART_SHR, LOG_SHR,
    BW_NOT, BW_AND, BW_OR,
    LOG_NOT, LOG_AND, LOG_OR,
    GREATER, LESS, EQ, NEQ, GEQ, LEQ,
    TYPE_CONV, RET,
    IF, ELSE, ELIF, WHILE, BREAK, CONT,
    LPAREN, RPAREN,
    LBRACKETS, RBRACKETS,
    COLON, SEMICOLON, COMMA, DOT, ASSIGNMENT,
    EOS
}
