package toks;

public enum TokType {
    UNKNOWN, VAR_DECL, CONST_DECL, FUN_DECL,
    ID, INT_LITERAL, FLOAT_LITERAL, BOOL_LITERAL,
    ADD, SUB, MUL, DIV, MOD, SHL, ART_SHR, LOG_SHR,
    BW_NOT, BW_AND, BW_OR,
    LOG_NOT, LOG_AND, LOG_OR,
    GREATER, LESS, EQ, NEQ, GEQ, LEQ,
    ARR_TYPE_CONV, TYPE_CONV, RET,
    IF, ELSE, ELIF, WHILE, BREAK, CONT,
    LPAREN, RPAREN,
    LCURLY, RCURLY,
    LSQUARE, RSQUARE,
    LANGLE, RANGLE,
    COLON, SEMI, COMMA, DOT, ASSIGNMENT,
    EOS
}
