package ast;

public enum ASTNodeType {
    LITERAL, ID, VAR_DECL, VAR_DEF, BIN_OP, UN_OP, SIMPLE_DTYPE, GENERIC_DTYPE, SCOPE, FUN_CALL, FUN_DEF, FUN_SIGN,
    PARAM_LIST, PARAM_DECL, RET, IF_ELSE, IF, ELSE, WHILE, BREAK, CONT, ARR_LITERAL,
    ARR_ACCESS, EXPR_LIST
}
