package ast;

public enum ASTNodeType {
    LITERAL, VAR_ID, CONST_ID, VAR_DECL, CONST_DECL, BIN_OP, UN_OP, VAR_DEF, CONST_DEF, DTYPE, SCOPE, FUN_CALL, FUN_DEF,
    PARAM_LIST, PARAM, PARAM_DECL, RET, IF_ELSE, IF, ELIF, ELSE, WHILE, TYPE_ANN, ID, BREAK, CONT
}
